# Generated by Django 2.2.4 on 2019-08-07 14:53

from django.db import migrations
import umc.models


class Migration(migrations.Migration):

    dependencies = [
        ('umc', '0002_auto_20190807_1435'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', umc.models.UserManager()),
            ],
        ),
    ]
